### ISSUE TITLE
No more friends?

### ISSUE THREAD

**Issue by rica-carv** [yesszus/another_profiles#2]
The friends "system" from old another_profiles has been removed?
I don't see the db table structure for it...

**Comment by yesszus** [comment]
This modified version.

**Comment by rica-carv** [comment]
Ah, so it's not the old legacy version upgraded to v2.x.....
But you're the original creator or no?
Or this version is only intended for you?
I'm asking this because i thought this plugin was not developed anymore, and i got a few updates & ideias for it, but i wanted to know if you intend to update it from the original or not...
Thanks

**Comment by yesszus** [comment]
I am not the original developer.
I'm trying to use the v2 version.
The development version no longer works for the developer.

**Comment by rica-carv** [comment]
Well, thanks for the info anyway.
Therefore, i'll try to make my own plugin, based on the v1.4 version ported to v2.x....
Thanks anyway....
